import Head from "next/head"

import { useEffect, useRef, useState } from "react"

import maplibregl from "maplibre-gl";
import * as pmtiles from "pmtiles";
import layer from "data/layers.json"

const Map = () => {
  const mapContainer = useRef(null);
  const map = useRef<maplibregl.Map>();
  const [lng] = useState(41.1533);
  const [lat] = useState(20.1683);

  const [zoom] = useState(2);

  useEffect(() => {
    if (map.current) return;

    let protocol = new pmtiles.Protocol();
    maplibregl.addProtocol("pmtiles", protocol.tile);

    map.current = new maplibregl.Map({
      container: mapContainer.current as unknown as HTMLElement,
      style: {
        glyphs: "/nextjs-protomap-demo/glyphs/{fontstack}/{range}.pbf",
        version: 8,
        "sources": {
          "openmaptiles": {
            "type": "vector",
            "url": "pmtiles:///nextjs-protomap-demo/switzerland.pmtiles"
          }
        },
        layers: layer as maplibregl.LayerSpecification[]
      },
      maxBounds: [            [
        3.215401694794508,
        45.333823182878035
      ], [
        12.051810391300307,
        48.11678780592885
      ],],
      minZoom: 5,
      center: [lng, lat],
      zoom: zoom
    });
  });

  return (
    <div className="map-wrap">
      <div ref={mapContainer} className="map" />
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Map></Map>
      </main>
    </>
  )
}
