import Head from "next/head"
import { useEffect, useRef, useState } from "react"

import maplibregl from "maplibre-gl";
import * as pmtiles from "pmtiles";
import layer from "data/positron_style.json"

const [initialLon, initialLat] = [-76.5059133431, 37.6227077717]

const Map = () => {
  const mapContainer = useRef(null);
  const map = useRef<maplibregl.Map>();
  const [lng] = useState(initialLon);
  const [lat] = useState(initialLat);

  const [zoom] = useState(7);

  useEffect(() => {
    if (map.current) return;

    let protocol = new pmtiles.Protocol();
    maplibregl.addProtocol("pmtiles", protocol.tile);

    map.current = new maplibregl.Map({
      container: mapContainer.current as unknown as HTMLElement,
      style: {
        glyphs: "/glyphs/{fontstack}/{range}.pbf",
        version: 8,
        "sources": {
          "openmaptiles": {
            "type": "vector",
            "url": "pmtiles:///maryland/maryland.pmtiles"
          },
          "isochrone": {
            "type": "vector",
            "url": "pmtiles:///maryland_iso.pmtiles",
          },
        },
        layers: layer as maplibregl.LayerSpecification[]
      },
      center: [lng, lat],
      zoom: zoom,
      customAttribution: "© OpenMapTiles © OpenStreetMap contributors"
    });
  });

  return (
    <div className="map-wrap">
      <div ref={mapContainer} className="map" />
      <div id="state-legend" className="legend">
        <h4>Driving Distance to Nearest Hospital</h4>
        <div className="legend-element"><span style={{ backgroundColor: "#fde725" }}></span>&lt; 10 minutes</div>
        <div className="legend-element"><span style={{ backgroundColor: "#35b779" }}></span>&lt; 20 minutes</div>
        <div className="legend-element"><span style={{ backgroundColor: "#31688e" }}></span>&lt; 30 minutes</div>
        <div className="legend-element"><span style={{ backgroundColor: "#440154" }}></span>&lt; 40 minutes</div>
      </div>
    </div>
  );
}


export default function Isochrone() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Map></Map>
      </main>
    </>
  )
}
